label = "duplicate"
output = "duplicate.json"
hyperfine_params = [  # common hyperfine parameters for all runs
    "--runs", "5",
    "--warmup", "3",
    "--parameter-list", "ifile", "Cargo.toml",
    "--parameter-list", "ofile", "/tmp/test.raw",
]

[run.past]
commits = ["master"] # can be hash, tag or branch
command = "dd if={ifile} of={ofile}"
setup = "cargo install --path sqsh-benchmark"
cleanup = "rm {ofile}"
# prepare = "" maybe empty cache

[run.reference]
command = "sqsh-cli duplicate {ifile} {ofile}"
setup = "cargo install --path sqsh-benchmark"

[run.control]
command = "dd if={ifile} of={ofile}"
